---
title: "Presentation"
subtitle: "&#x2694;&#xFE0F; xaringan +<br/>&#x1F60E; xaringanthemer"  
author: 
  - "Yezi He"
  - "Priya Ravindra Dingorkar"
date: '`r Sys.Date()`'
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: xaringan-themer.css
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE,
        warning = FALSE)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_duo_accent(
  primary_color = "#1381B0",
  secondary_color = "#FF961C",
  inverse_header_color = "#FFFFFF"
)
```

```{r library}
library(tidyverse)
library(stringr)
library(lubridate)
```


```{r readadta}
location <- read_csv(here::here("data/Microclimate_Sensor_Locations.csv"))
readings <- read_csv(here::here("data/Microclimate_Sensor_Readings.csv")) 
ws <- readings %>% filter(type == "WS") %>%
  mutate(date = as.Date(local_time),
         time = str_sub(as_datetime(local_time),12))
  
```

```{r fourseasons}
seansons <- ws %>%
  mutate(season = case_when(month(date) == c(12,1,2) ~ "summer",
                   month(date) == c(3,4,5) ~ "autumn",
                   month(date) == c(6,7,8) ~ "winter",
                   TRUE ~ "spring"))
```



